### PR TITLE
Switch template

### PR DESCRIPTION
**Pull request by CxRes**

### CODE REVIEW

**Comment by elf-pavlik** [comment]
I suggest waiting for https://github.com/speced/bikeshed/pull/2875 and removing the custom copyright and status of the document.

**Comment by elf-pavlik** [comment]
bikeshed-boilerplate already has solidcg copyright and stod https://github.com/speced/bikeshed-boilerplate/pull/83

Example commit to use those default includes https://github.com/solid/security-considerations/commit/0eb62ee2323757d3e37b245951b2bcb86c9a0030

result: https://solid.github.io/security-considerations/

**Comment by CxRes** [comment]
Thanks for letting me know! I am going to hold off on all changes until it is made explicit that this work will be permissively licensed by the CG to the general public in the copyright statement.

**Comment by elf-pavlik** [comment]
Who are you asking for clarifications from, and where do you track it?

**Comment by CxRes** [comment]
Licensing concerns are tracked in https://github.com/solid/specification/issues/587#issuecomment-2225557756. I am closing this issue to work on other issues in the repository. Will revisit upon resolution or otherwise.

**Pull request closed without merging**
